name: Build linux Executable (onedir)

on:
  workflow_dispatch:  # ⬅️ permet de lancer manuellement

jobs:
  build-linux:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
          
      - name: Clean build and dist folders
        run: |
          import shutil
          shutil.rmtree('build', ignore_errors=True)
          shutil.rmtree('dist', ignore_errors=True)
          shutil.rmtree('__pycache__', ignore_errors=True)
        shell: python

      - name: Build with PyInstaller (.spec)
        run: pyinstaller inti.spec

      - name: Liste les fichiers générés
        run: ls -lh dist/inti/
        
      - name: Copier le PDF et le dossier d'exemples
        run: |
          cp inti_om_FR.pdf dist/inti/

      #- name: Créer le fichier ZIP
      #  run: |
      #    zip -r inti-linux.zip dist/inti
          
      - name: Upload artefact sans zip imbriqué
        uses: actions/upload-artifact@v4
        with:
          name: inti-linux
          path: dist/inti/
